services:
  - type: web
    name: etm-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true
